name: hogastos
description: "Hogastos is an application to control your home accounts."
publish_to: 'none'

version: 1.2.0+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  crypto: ^3.0.6
  d_chart: ^2.9.1
  drift: ^2.23.1
  drift_flutter: ^0.1.0
  excel: ^4.0.6
  flutter_animate: ^4.5.0
  flutter_iconpicker: ^4.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  local_auth: ^2.3.0
  local_auth_android: ^1.0.46
  money2: ^5.4.6
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  drift_dev: ^2.23.1

flutter:
  generate: true
  uses-material-design: true
