name: hogastos
description: "Hogastos is an application to control your home accounts."
publish_to: 'none'

version: 1.5.1+8

environment:
  sdk: ^3.7.0

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^5.1.1
  crypto: ^3.0.6
  d_chart: ^3.0.0
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  excel: ^4.0.6
  flutter_animate: ^4.5.0
  flutter_file_dialog: ^3.0.2
  flutter_launcher_icons: ^0.14.3
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.2
  jiffy: ^6.4.3
  local_auth: ^2.3.0
  local_auth_android: ^1.0.46
  pin_code_fields: ^8.0.1
  skeletonizer: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  drift_dev: ^2.23.1

flutter:
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
